In [1]:
import jax.numpy as jnp
import numpy as np

In [2]:
file_path = "/Users/haifeng/Program/FUEL-JAX/input/jax_lax_abs/case_000.npz"

In [4]:
data = np.load(file_path)

In [5]:
data.files

['x']

In [10]:
x = data["x"]
print(x.shape, x.dtype)
x

(5,) float32


array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [8]:
x_jax = jnp.array(x)

In [9]:
x_jax

Array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [11]:
import torch

x_torch = torch.from_numpy(x)

In [13]:
x_torch.to(device="cpu")

tensor([-1., -2.,  3., -4.,  5.])

In [14]:
import jax.lax as lax
import jax.numpy as jnp
from jax import jit
import torch

In [15]:
op_name = "abs"
input_data = jnp.array([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=jnp.float32)

op_func = getattr(lax, op_name)
jitted_op_func = jit(op_func)
jax_output = jitted_op_func(input_data)
torch_input = torch.tensor([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=torch.float32)
torch_op_func = getattr(torch, op_name)
torch_output = torch_op_func(torch_input)
print("JAX Output:", jax_output)
print("PyTorch Output:", torch_output)

JAX Output: [1. 2. 3. 4. 5.]
PyTorch Output: tensor([1., 2., 3., 4., 5.])


In [16]:
torch.cbrt(torch_input)

AttributeError: module 'torch' has no attribute 'cbrt'

In [1]:
import torch

In [4]:
x1 = torch.tensor([1, 2, 3, 4], dtype=torch.float8_e4m3fn)
x2 = torch.tensor([1, 2, 3, 4], dtype=torch.bfloat16)

In [5]:
def fn(x):
    return torch.rsqrt(x)


fn_compile = torch.compile(fn)

In [8]:
fn(x2)
fn_compile(x2)

tensor([1.0000, 0.7070, 0.5781, 0.5000], dtype=torch.bfloat16)

In [9]:
fn_compile(x1)

InductorError: CppCompileError: C++ compile error

Command:
clang++ /var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/kw/ckwfd5jh2pwkdjdqkpcrqmzdzjmput2ngnm5pyjcwcpgtsthdpfv.main.cpp -D TORCH_INDUCTOR_CPP_WRAPPER -D STANDALONE_TORCH_HEADER -D C10_USING_CUSTOM_GENERATED_MACROS -D CPU_CAPABILITY_NEON -D AT_BUILD_ARM_VEC256_WITH_SLEEF -O3 -DNDEBUG -fno-trapping-math -funsafe-math-optimizations -ffinite-math-only -fno-signed-zeros -fno-math-errno -fno-finite-math-only -fno-unsafe-math-optimizations -ffp-contract=off -shared -fPIC -undefined dynamic_lookup -Wall -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -Werror=ignored-optimization-argument -Xclang -fopenmp -include /var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/precompiled_headers/czkes42gdobd5o3vwhwmltadasnzrzkzt626xzknkl4wevejxgbb.h -I/Users/haifeng/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/include/python3.12 -I/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include -I/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -o /var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/kw/ckwfd5jh2pwkdjdqkpcrqmzdzjmput2ngnm5pyjcwcpgtsthdpfv.main.so -lomp -L/Users/haifeng/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib -L/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/lib

Output:
In file included from /var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/kw/ckwfd5jh2pwkdjdqkpcrqmzdzjmput2ngnm5pyjcwcpgtsthdpfv.main.cpp:1:
In file included from /var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/precompiled_headers/czkes42gdobd5o3vwhwmltadasnzrzkzt626xzknkl4wevejxgbb.h:1:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/torch/csrc/inductor/cpp_prefix.h:45:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/functional.h:4:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/functional_base.h:7:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec.h:7:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec128/vec128.h:9:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec128/vec128_bfloat16_neon.h:6:
In file included from /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec128/vec128_float_neon.h:8:
/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec_base.h:679:12: error: no matching member function for call to 'map'
  679 |     return map([](T x) { return (T)1 / std::sqrt(x); });
      |            ^~~
/var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/torchinductor_haifeng/kw/ckwfd5jh2pwkdjdqkpcrqmzdzjmput2ngnm5pyjcwcpgtsthdpfv.main.cpp:13:38: note: in instantiation of member function 'at::vec::Vectorized<c10::Float8_e4m3fn>::rsqrt' requested here
   13 |                     auto tmp1 = tmp0.rsqrt();
      |                                      ^
/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec_base.h:351:17: note: candidate function not viable: no known conversion from '(lambda at /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec_base.h:679:16)' to 'c10::Float8_e4m3fn (*const)(c10::Float8_e4m3fn)' for 1st argument
  351 |   Vectorized<T> map(T (*const f)(T)) const {
      |                 ^   ~~~~~~~~~~~~~~~
/Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec_base.h:366:17: note: candidate function not viable: no known conversion from '(lambda at /Users/haifeng/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/torch/include/ATen/cpu/vec/vec_base.h:679:16)' to 'c10::Float8_e4m3fn (*const)(const c10::Float8_e4m3fn &)' for 1st argument
  366 |   Vectorized<T> map(T (*const f)(const T&)) const {
      |                 ^   ~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"


In [ ]:
fn_compile()