In [1]:
import jax.numpy as jnp
import numpy as np

In [2]:
file_path = "/Users/haifeng/Program/FUEL-JAX/input/jax_lax_abs/case_000.npz"

In [4]:
data = np.load(file_path)

In [5]:
data.files

['x']

In [10]:
x = data["x"]
print(x.shape, x.dtype)
x

(5,) float32


array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [8]:
x_jax = jnp.array(x)

In [9]:
x_jax

Array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [11]:
import torch

x_torch = torch.from_numpy(x)

In [13]:
x_torch.to(device="cpu")

tensor([-1., -2.,  3., -4.,  5.])

In [14]:
import jax.numpy as jnp
import torch