In [1]:
import jax.numpy as jnp
import numpy as np

In [2]:
file_path = "/Users/haifeng/Program/FUEL-JAX/input/jax_lax_abs/case_000.npz"

In [4]:
data = np.load(file_path)

In [5]:
data.files

['x']

In [10]:
x = data["x"]
print(x.shape, x.dtype)
x

(5,) float32


array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [8]:
x_jax = jnp.array(x)

In [9]:
x_jax

Array([-1., -2.,  3., -4.,  5.], dtype=float32)

In [11]:
import torch

x_torch = torch.from_numpy(x)

In [13]:
x_torch.to(device="cpu")

tensor([-1., -2.,  3., -4.,  5.])

In [14]:
import jax.lax as lax
import jax.numpy as jnp
from jax import jit
import torch

In [15]:
op_name = "abs"
input_data = jnp.array([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=jnp.float32)

op_func = getattr(lax, op_name)
jitted_op_func = jit(op_func)
jax_output = jitted_op_func(input_data)
torch_input = torch.tensor([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=torch.float32)
torch_op_func = getattr(torch, op_name)
torch_output = torch_op_func(torch_input)
print("JAX Output:", jax_output)
print("PyTorch Output:", torch_output)

JAX Output: [1. 2. 3. 4. 5.]
PyTorch Output: tensor([1., 2., 3., 4., 5.])


In [16]:
torch.cbrt(torch_input)

AttributeError: module 'torch' has no attribute 'cbrt'