In [3]:
import jax
import jax.numpy as jnp
from jax import lax
import torch
import numpy as np

In [4]:
### abs

inp = jnp.array([-1.0, 2.0, -3.0])
out = jnp.abs(inp)
print("JAX abs:", out)

JAX abs: [1. 2. 3.]


In [5]:
jax.lax.acos(inp)

Array([3.1415925,       nan,       nan], dtype=float32)

In [6]:
lax.max(inp, inp)

Array([-1.,  2., -3.], dtype=float32)

In [7]:
x1 = np.random.rand(3, 4).astype(np.float32)

In [14]:
lax.argmax(x1, axis=0, index_dtype=jnp.int32)

Array([2, 2, 0, 0], dtype=int32)

In [16]:
torch.argmax(torch.tensor(x1), dim=0, index_type=torch.int32)

TypeError: argmax() got an unexpected keyword argument 'index_type'

In [19]:
lax.abs(x=inp)

Array([1., 2., 3.], dtype=float32)

In [20]:
lax.argmax(operand=x1, axis=0, index_dtype=jnp.int32)

Array([2, 2, 0, 0], dtype=int32)

In [29]:
lax.approx_max_k(operand=inp, k=2, reduction_dimension=0, recall_target=0.5)

[Array([ 2., -1.], dtype=float32), Array([1, 0], dtype=int32)]

In [32]:
import inspect


inspect.signature(lax.approx_max_k)

<Signature (operand: jax.Array, k: int, reduction_dimension: int = -1, recall_target: float = 0.95, reduction_input_size_override: int = -1, aggregate_to_topk: bool = True) -> tuple[jax.Array, jax.Array]>

In [34]:
inspect.signature(torch.topk)

ValueError: no signature found for builtin <built-in method topk of type object at 0x1105ff6d0>

In [36]:
file_path = "/Users/haifeng/Program/FUEL-JAX/input/abs/01.npz"

In [37]:
x = np.random.rand(3, 4).astype(np.float32)

np.savez_compressed(file_path, x=x)

In [43]:
data = np.load("/Users/haifeng/Program/FUEL-JAX/output/abs/test.npz")

In [44]:
data

NpzFile '/Users/haifeng/Program/FUEL-JAX/output/abs/test.npz' with keys: out

In [45]:
data["out"]

array([[0.62513006, 0.6944465 , 0.5826604 , 0.85714823],
       [0.22155215, 0.16254286, 0.36576876, 0.6015664 ],
       [0.39712742, 0.23268753, 0.14461608, 0.5430027 ]], dtype=float32)

In [47]:
data.keys()

KeysView(NpzFile '/Users/haifeng/Program/FUEL-JAX/output/abs/test.npz' with keys: out)