In [1]:
import jax.lax as lax
import torch
import jax.numpy as jnp
import numpy as np

In [3]:
lax.clz(jnp.array([1, 2, 3], dtype=jnp.int32))
x = torch.tensor([1, 2, 3], dtype=torch.int32)
x.clz()

AttributeError: 'Tensor' object has no attribute 'clz'

In [16]:
x = jnp.array([1, 2, 3], dtype=jnp.float32)
y = jnp.int64(2)
lax.integer_pow(x, y)

/Users/lhf/Program/FUEL-JAX/.venv/lib/python3.12/site-packages/jax/_src/numpy/scalar_types.py:55: UserWarning: Explicitly requested dtype int64 requested in asarray is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  return asarray(x, dtype=self.dtype)


TypeError: unhashable type: 'jaxlib._jax.ArrayImpl'

In [8]:
lax.imag(jnp.array([1 + 2j, 3 + 4j]))

Array([2., 4.], dtype=float32)

In [7]:
import jax.lax as lax
import jax.numpy as jnp

op_name = "abs"
input_data = jnp.array([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=jnp.float32)

inp = {"x": input_data}

op_func = getattr(lax, op_name)

op_func(**inp)

Array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
import torch

y = torch.tensor([-1.0, -2.0, 3.0, -4.0, 5.0], dtype=torch.float32)
op_name = "abs"

inp = [y]

op_func = getattr(torch, op_name)
op_func(*inp)

tensor([1., 2., 3., 4., 5.])

In [14]:
import inspect

inspect.signature(abs)

<Signature (x, /)>

In [18]:
import torch
import inspect

inspect.signature(torch.abs)

ValueError: no signature found for builtin <built-in method abs of type object at 0x1166736d0>

In [21]:
out_file = "/Users/lhf/Program/FUEL-JAX/output/abs/FP8_E5M2/out_jax_cpu.npz"
data = np.load(out_file)
print(data["out_jax_cpu"])

[[ 2.5  5.  10. ]
 [10.   6.   8. ]]


In [22]:
import numpy as np

out_file = "/Users/lhf/Program/FUEL-JAX/output/abs/FP8_E4M3/out_jax_cpu.npz"
data = np.load(out_file)
print(data["out_jax_cpu"])

[[ 2.75  4.5   9.  ]
 [10.    6.5   8.  ]]


In [23]:
import numpy as np

out_file = "/Users/lhf/Program/FUEL-JAX/output/abs/FP32/out_jax_cpu.npz"
data = np.load(out_file)
print(data["out_jax_cpu"])

[[2.7392337 4.6042657 9.18053  ]
 [9.669447  6.2654047 8.255112 ]]


In [24]:
import numpy as np

out_file = "/Users/lhf/Program/FUEL-JAX/output/abs/BF16/out_jax_cpu.npz"
data = np.load(out_file)
print(data["out_jax_cpu"])

[[2.734375 4.59375  9.1875  ]
 [9.6875   6.25     8.25    ]]
