In [1]:
import torch
import jax.numpy as jnp
import numpy as np
import jax

In [2]:
data = np.load("/Users/haifeng/Program/FUEL-JAX/input/jax.lax.integer_pow/00.npz")
x = data["x"]
y = data["y"]

In [3]:
j_x = jnp.array(x, dtype=jnp.float32)
j_y = int(y)
t_x = torch.from_numpy(x).to(torch.float32)
t_y = torch.tensor(y)

In [4]:
j_out = jax.lax.integer_pow(j_x, j_y)
j_out

Array([[-0.0000000e+00, -7.4097744e-25, -5.5688051e+08, -1.4754315e+14,
         0.0000000e+00,  0.0000000e+00,  4.8287901e+20, -0.0000000e+00],
       [ 3.6439347e+00,  5.2961414e+04, -0.0000000e+00,  0.0000000e+00,
        -4.2849508e-23,  1.5976299e+15, -7.7637599e+10, -0.0000000e+00],
       [ 4.0893610e+08, -0.0000000e+00, -1.4187406e-15,  0.0000000e+00,
         1.0711378e-17,  9.7557433e-16,  2.7018740e-34,  2.4096629e-08],
       [ 3.3188436e-02, -4.9000772e+02, -1.9472810e-26,  2.0011202e-04,
         1.0647474e-19,  0.0000000e+00,  3.0789243e-11,  5.0249454e-02]],      dtype=float32)

In [5]:
t_out = torch.ops.aten.pow.Tensor_Tensor(t_x, t_y)
t_out

tensor([[-0.0000e+00, -7.4098e-25, -5.5688e+08, -1.4754e+14,  0.0000e+00,
          0.0000e+00,  4.8288e+20, -0.0000e+00],
        [ 3.6439e+00,  5.2961e+04, -0.0000e+00,  0.0000e+00, -4.2850e-23,
          1.5976e+15, -7.7638e+10, -0.0000e+00],
        [ 4.0894e+08, -0.0000e+00, -1.4187e-15,  2.4852e-39,  1.0711e-17,
          9.7557e-16,  2.7019e-34,  2.4097e-08],
        [ 3.3188e-02, -4.9001e+02, -1.9473e-26,  2.0011e-04,  1.0647e-19,
          3.8906e-39,  3.0789e-11,  5.0250e-02]])

In [6]:
t_out_1 = torch.ops.aten.pow.Tensor_Scalar(t_x, int(t_y))
t_out_1

tensor([[-0.0000e+00, -7.4098e-25, -5.5688e+08, -1.4754e+14,  0.0000e+00,
          0.0000e+00,  4.8288e+20, -0.0000e+00],
        [ 3.6439e+00,  5.2961e+04, -0.0000e+00,  0.0000e+00, -4.2850e-23,
          1.5976e+15, -7.7638e+10, -0.0000e+00],
        [ 4.0894e+08, -0.0000e+00, -1.4187e-15,  2.4852e-39,  1.0711e-17,
          9.7557e-16,  2.7019e-34,  2.4097e-08],
        [ 3.3188e-02, -4.9001e+02, -1.9473e-26,  2.0011e-04,  1.0647e-19,
          3.8906e-39,  3.0789e-11,  5.0250e-02]])

In [7]:
t_out - t_out_1

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
j_out_torch = torch.from_numpy(np.array(j_out))
j_out_torch

tensor([[-0.0000e+00, -7.4098e-25, -5.5688e+08, -1.4754e+14,  0.0000e+00,
          0.0000e+00,  4.8288e+20, -0.0000e+00],
        [ 3.6439e+00,  5.2961e+04, -0.0000e+00,  0.0000e+00, -4.2850e-23,
          1.5976e+15, -7.7638e+10, -0.0000e+00],
        [ 4.0894e+08, -0.0000e+00, -1.4187e-15,  0.0000e+00,  1.0711e-17,
          9.7557e-16,  2.7019e-34,  2.4097e-08],
        [ 3.3188e-02, -4.9001e+02, -1.9473e-26,  2.0011e-04,  1.0647e-19,
          0.0000e+00,  3.0789e-11,  5.0249e-02]])

In [9]:
diff = torch.abs(j_out_torch - t_out).flatten()

In [10]:
diff

tensor([0.0000e+00, 3.4513e-31, 5.7600e+02, 2.5166e+08, 0.0000e+00, 0.0000e+00,
        1.0555e+14, 0.0000e+00, 3.0994e-06, 1.1719e-02, 0.0000e+00, 0.0000e+00,
        1.5777e-29, 6.7109e+08, 9.0112e+04, 0.0000e+00, 2.5600e+02, 0.0000e+00,
        1.2705e-21, 2.4852e-39, 1.0753e-23, 3.1764e-22, 6.8877e-41, 1.4211e-14,
        2.2352e-08, 1.8311e-04, 3.3896e-32, 5.8208e-11, 7.1086e-26, 3.8906e-39,
        3.4694e-18, 5.2154e-08])

In [11]:
max_diff = torch.argmax(diff)

In [12]:
import torch
import numpy as np


def get_ulp_diff_matrix_float(pred, truth):
    """
    计算 ULP 差异矩阵 (浮点数版本)。
    表示 pred 和 truth 之间相差了多少个机器精度单位。
    """
    # 1. 确保转为 Numpy 且为 float32
    a = np.array(pred, dtype=np.float32)
    b = np.array(truth, dtype=np.float32)

    # 2. 计算绝对误差
    abs_diff = np.abs(a - b)

    # 3. 计算真值处的 1 ULP 长度 (Gap size)
    # np.spacing(x) 返回 x 到下一个可表示浮点数的距离
    gap = np.spacing(b)

    # 4. 处理除零风险 (当 b=0 时，gap=0)
    # 0 处的 ULP 通常定义为最小正非零数 (subnormal min) 或 min normal
    # 这里我们用 float32 的最小正数填充，避免 NaN
    min_val = np.finfo(np.float32).tiny  # 约 1.17e-38
    gap[gap == 0] = min_val

    # 5. 计算比率
    ulp_diff = abs_diff / gap

    return ulp_diff


# === 使用示例 ===
# j_out_torch 和 t_out 是你的张量
# ulp_matrix = get_ulp_diff_matrix_float(j_out_torch, t_out)

# print("最大 ULP 误差:", np.max(ulp_matrix))
# print("平均 ULP 误差:", np.mean(ulp_matrix))

In [13]:
j_out_torch

tensor([[-0.0000e+00, -7.4098e-25, -5.5688e+08, -1.4754e+14,  0.0000e+00,
          0.0000e+00,  4.8288e+20, -0.0000e+00],
        [ 3.6439e+00,  5.2961e+04, -0.0000e+00,  0.0000e+00, -4.2850e-23,
          1.5976e+15, -7.7638e+10, -0.0000e+00],
        [ 4.0894e+08, -0.0000e+00, -1.4187e-15,  0.0000e+00,  1.0711e-17,
          9.7557e-16,  2.7019e-34,  2.4097e-08],
        [ 3.3188e-02, -4.9001e+02, -1.9473e-26,  2.0011e-04,  1.0647e-19,
          0.0000e+00,  3.0789e-11,  5.0249e-02]])

In [14]:
t_out

tensor([[-0.0000e+00, -7.4098e-25, -5.5688e+08, -1.4754e+14,  0.0000e+00,
          0.0000e+00,  4.8288e+20, -0.0000e+00],
        [ 3.6439e+00,  5.2961e+04, -0.0000e+00,  0.0000e+00, -4.2850e-23,
          1.5976e+15, -7.7638e+10, -0.0000e+00],
        [ 4.0894e+08, -0.0000e+00, -1.4187e-15,  2.4852e-39,  1.0711e-17,
          9.7557e-16,  2.7019e-34,  2.4097e-08],
        [ 3.3188e-02, -4.9001e+02, -1.9473e-26,  2.0011e-04,  1.0647e-19,
          3.8906e-39,  3.0789e-11,  5.0250e-02]])

In [15]:
get_ulp_diff_matrix_float(j_out_torch, t_out)

/var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/ipykernel_60745/2337834513.py:10: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  a = np.array(pred, dtype=np.float32)
/var/folders/4q/td31czvd29qc_qk6bh070n680000gn/T/ipykernel_60745/2337834513.py:11: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  b = np.array(truth, dtype=np.float32)


array([[ 0.000000e+00, -7.000000e+00, -9.000000e+00, -1.500000e+01,
         0.000000e+00,  0.000000e+00,  3.000000e+00,  0.000000e+00],
       [ 1.300000e+01,  3.000000e+00,  0.000000e+00,  0.000000e+00,
        -5.000000e+00,  5.000000e+00, -1.100000e+01,  0.000000e+00],
       [ 8.000000e+00,  0.000000e+00, -1.200000e+01,  1.773506e+06,
         1.300000e+01,  3.000000e+00,  3.000000e+00,  8.000000e+00],
       [ 6.000000e+00, -6.000000e+00, -2.200000e+01,  4.000000e+00,
         1.100000e+01,  2.776454e+06,  1.000000e+00,  1.400000e+01]],
      dtype=float32)