### 测试 jax.lax.round 算子

In [1]:
import torch
import jax.numpy as jnp
import numpy as np
import jax

In [2]:
data = np.load("/Users/haifeng/Program/FUEL-JAX/input/jax.lax.polygamma/00.npz")
m = data["m"]
x = data["x"]
print(m)
x

3


array([[ 3.5155892e+00, -9.9014664e+00,  5.2350583e+00,  2.5362356e+00,
         8.9597292e+00,  8.6089153e+00, -1.5643225e+00, -7.7771873e+00],
       [-1.6095866e+00, -2.0636640e+00,  4.4253463e-04, -5.0145383e+00,
        -3.4753771e+00, -8.7194643e+00,  5.0481744e+00, -4.4130483e+00],
       [ 3.6164651e+00, -4.4654341e+00,  6.8272390e+00, -5.2350836e+00,
        -7.5879312e+00,  5.6201315e+00, -5.4381948e+00, -6.5086985e+00],
       [ 1.4191039e+00, -8.7506580e+00,  1.1702731e+00, -9.6326857e+00,
        -1.4321250e+00, -1.6942199e+00, -8.2911930e+00, -8.3586006e+00]],
      dtype=float32)

In [3]:
j_m = m.astype(jnp.float32)
j_x = jnp.array(x, dtype=jnp.float32)
t_m = int(m)
t_x = torch.from_numpy(x).to(torch.float32)

In [4]:
j_out = jax.lax.polygamma(j_m, j_x)
j_out

Array([[ 6.9256395e-02, -8.3809897e+34,  1.8434145e-02,  2.1290655e-01,
         3.2805966e-03,  3.7228055e-03,  2.2835094e+02,  2.4546040e+03],
       [ 3.0447079e+02,  3.6525225e+05,  1.5644532e+14,  1.3430699e+08,
         1.9949028e+02, -6.3589297e+04,  2.0764345e-02,  2.5957251e+02],
       [ 6.2942602e-02,  2.0414699e+02,  7.7991136e-03,  1.9857500e+03,
         2.6121600e+02,  1.4624837e-02,  2.2581659e+02,  1.9539513e+02],
       [ 1.7307355e+00, -1.2465161e+05,  3.5678053e+00, -3.0957838e+19,
         2.3239203e+02,  7.1522363e+02,  8.3658441e+02,  3.2631628e+02]],      dtype=float32)

In [5]:
t_out = torch.ops.aten.special_polygamma.default(t_m, t_x)
t_out

tensor([[6.9256e-02, 6.3666e+04, 1.8434e-02, 2.1291e-01, 3.2806e-03, 3.7228e-03,
         2.2835e+02, 2.4546e+03],
        [3.0447e+02, 3.6525e+05, 1.5645e+14, 1.3431e+08, 1.9949e+02, 9.9451e+02,
         2.0764e-02, 2.5957e+02],
        [6.2943e-02, 2.0415e+02, 7.7991e-03, 1.9857e+03, 2.6122e+02, 1.4625e-02,
         2.2582e+02, 1.9539e+02],
        [1.7307e+00, 1.5748e+03, 3.5678e+00, 3.7007e+02, 2.3239e+02, 7.1522e+02,
         8.6161e+02, 4.0133e+02]])

In [6]:
print(jax.scipy.special.polygamma(int(j_m), j_x))
print(torch.special.polygamma(t_m, t_x))

[[ 6.9256395e-02 -8.3809897e+34  1.8434145e-02  2.1290655e-01
   3.2805966e-03  3.7228055e-03  2.2835094e+02  2.4546040e+03]
 [ 3.0447079e+02  3.6525225e+05  1.5644532e+14  1.3430699e+08
   1.9949028e+02 -6.3589297e+04  2.0764345e-02  2.5957251e+02]
 [ 6.2942602e-02  2.0414699e+02  7.7991136e-03  1.9857500e+03
   2.6121600e+02  1.4624837e-02  2.2581659e+02  1.9539513e+02]
 [ 1.7307355e+00 -1.2465161e+05  3.5678053e+00 -3.0957838e+19
   2.3239203e+02  7.1522363e+02  8.3658441e+02  3.2631628e+02]]
tensor([[6.9256e-02, 6.3666e+04, 1.8434e-02, 2.1291e-01, 3.2806e-03, 3.7228e-03,
         2.2835e+02, 2.4546e+03],
        [3.0447e+02, 3.6525e+05, 1.5645e+14, 1.3431e+08, 1.9949e+02, 9.9451e+02,
         2.0764e-02, 2.5957e+02],
        [6.2943e-02, 2.0415e+02, 7.7991e-03, 1.9857e+03, 2.6122e+02, 1.4625e-02,
         2.2582e+02, 1.9539e+02],
        [1.7307e+00, 1.5748e+03, 3.5678e+00, 3.7007e+02, 2.3239e+02, 7.1522e+02,
         8.6161e+02, 4.0133e+02]])


In [7]:
# 输入 x < 0
print(f"input:{x[0][1]}")
print(f"jax_out:{j_out[0][1]}")
print(f"torch_out:{t_out[0][1].numpy()}")

input:-9.901466369628906
jax_out:-8.38098974419033e+34
torch_out:63666.3984375


In [8]:
# 输入 x > 0
print(f"input:{x[0][0]}")
print(f"jax_out:{j_out[0][0]}")
print(f"torch_out:{t_out[0][0].numpy()}")

input:3.5155892372131348
jax_out:0.06925639510154724
torch_out:0.06925633549690247


## 说明，这两个函数在 输入是正数的时候是一致的

In [9]:
x = np.abs(x) + 0.001
j_x = jnp.array(x, dtype=jnp.float32)
t_x = torch.from_numpy(x).to(torch.float32)

In [10]:
x

array([[3.5165892e+00, 9.9024668e+00, 5.2360582e+00, 2.5372355e+00,
        8.9607296e+00, 8.6099157e+00, 1.5653225e+00, 7.7781873e+00],
       [1.6105866e+00, 2.0646639e+00, 1.4425346e-03, 5.0155382e+00,
        3.4763770e+00, 8.7204647e+00, 5.0491743e+00, 4.4140482e+00],
       [3.6174650e+00, 4.4664340e+00, 6.8282390e+00, 5.2360835e+00,
        7.5889311e+00, 5.6211314e+00, 5.4391947e+00, 6.5096984e+00],
       [1.4201039e+00, 8.7516584e+00, 1.1712731e+00, 9.6336861e+00,
        1.4331250e+00, 1.6952200e+00, 8.2921934e+00, 8.3596010e+00]],
      dtype=float32)

In [11]:
j_out = jax.lax.polygamma(j_m, j_x)
j_out

Array([[6.9189779e-02, 2.3925765e-03, 1.8422635e-02, 2.1261325e-01,
        3.2794382e-03, 3.7214351e-03, 1.2039796e+00, 5.1393537e-03],
       [1.0841630e+00, 4.4072482e-01, 1.3856280e+12, 2.1210805e-02,
        7.1936771e-02, 3.5740205e-03, 2.0750863e-02, 3.2322627e-02],
       [6.2883906e-02, 3.1083513e-02, 7.7954470e-03, 1.8422343e-02,
        5.5592884e-03, 1.4616376e-02, 1.6269572e-02, 9.0899169e-03],
       [1.7262076e+00, 3.5338341e-03, 3.5562904e+00, 2.6092057e-03,
        1.6686300e+00, 8.9875692e-01, 4.1928650e-03, 4.0864707e-03]],      dtype=float32)

In [12]:
t_out = torch.ops.aten.special_polygamma.default(t_m, t_x)
t_out

tensor([[6.9190e-02, 2.3926e-03, 1.8423e-02, 2.1261e-01, 3.2794e-03, 3.7214e-03,
         1.2040e+00, 5.1393e-03],
        [1.0842e+00, 4.4072e-01, 1.3856e+12, 2.1211e-02, 7.1937e-02, 3.5740e-03,
         2.0751e-02, 3.2323e-02],
        [6.2884e-02, 3.1083e-02, 7.7954e-03, 1.8422e-02, 5.5593e-03, 1.4616e-02,
         1.6270e-02, 9.0899e-03],
        [1.7262e+00, 3.5338e-03, 3.5563e+00, 2.6092e-03, 1.6686e+00, 8.9876e-01,
         4.1929e-03, 4.0865e-03]])

In [13]:
j_out_np = np.array(j_out, dtype=np.float64)
j_out_np

array([[6.91897795e-02, 2.39257654e-03, 1.84226353e-02, 2.12613255e-01,
        3.27943824e-03, 3.72143509e-03, 1.20397961e+00, 5.13935369e-03],
       [1.08416295e+00, 4.40724820e-01, 1.38562804e+12, 2.12108046e-02,
        7.19367713e-02, 3.57402046e-03, 2.07508635e-02, 3.23226266e-02],
       [6.28839061e-02, 3.10835131e-02, 7.79544702e-03, 1.84223428e-02,
        5.55928843e-03, 1.46163758e-02, 1.62695721e-02, 9.08991694e-03],
       [1.72620761e+00, 3.53383413e-03, 3.55629039e+00, 2.60920567e-03,
        1.66863000e+00, 8.98756921e-01, 4.19286499e-03, 4.08647070e-03]])

In [14]:
t_out_np = t_out.detach().cpu().to(torch.float64).numpy()
t_out_np

array([[6.91897199e-02, 2.39257421e-03, 1.84226166e-02, 2.12613016e-01,
        3.27943498e-03, 3.72143183e-03, 1.20397842e+00, 5.13934856e-03],
       [1.08416212e+00, 4.40724432e-01, 1.38562686e+12, 2.12107822e-02,
        7.19367117e-02, 3.57401697e-03, 2.07508467e-02, 3.23226005e-02],
       [6.28838539e-02, 3.10834888e-02, 7.79544003e-03, 1.84223261e-02,
        5.55928424e-03, 1.46163646e-02, 1.62695590e-02, 9.08990949e-03],
       [1.72620630e+00, 3.53383087e-03, 3.55628729e+00, 2.60920357e-03,
        1.66862845e+00, 8.98756146e-01, 4.19286080e-03, 4.08646697e-03]])

In [15]:
diff = np.abs(j_out_np - t_out_np)
diff

array([[5.96046448e-08, 2.32830644e-09, 1.86264515e-08, 2.38418579e-07,
        3.25962901e-09, 3.25962901e-09, 1.19209290e-06, 5.12227416e-09],
       [8.34465027e-07, 3.87430191e-07, 1.17964800e+06, 2.23517418e-08,
        5.96046448e-08, 3.49245965e-09, 1.67638063e-08, 2.60770321e-08],
       [5.21540642e-08, 2.42143869e-08, 6.98491931e-09, 1.67638063e-08,
        4.19095159e-09, 1.11758709e-08, 1.30385160e-08, 7.45058060e-09],
       [1.31130219e-06, 3.25962901e-09, 3.09944153e-06, 2.09547579e-09,
        1.54972076e-06, 7.74860382e-07, 4.19095159e-09, 3.72529030e-09]])

In [16]:
diff = diff.flatten()

In [17]:
diff

array([5.96046448e-08, 2.32830644e-09, 1.86264515e-08, 2.38418579e-07,
       3.25962901e-09, 3.25962901e-09, 1.19209290e-06, 5.12227416e-09,
       8.34465027e-07, 3.87430191e-07, 1.17964800e+06, 2.23517418e-08,
       5.96046448e-08, 3.49245965e-09, 1.67638063e-08, 2.60770321e-08,
       5.21540642e-08, 2.42143869e-08, 6.98491931e-09, 1.67638063e-08,
       4.19095159e-09, 1.11758709e-08, 1.30385160e-08, 7.45058060e-09,
       1.31130219e-06, 3.25962901e-09, 3.09944153e-06, 2.09547579e-09,
       1.54972076e-06, 7.74860382e-07, 4.19095159e-09, 3.72529030e-09])

In [18]:
diff.sort()

In [19]:
diff

array([2.09547579e-09, 2.32830644e-09, 3.25962901e-09, 3.25962901e-09,
       3.25962901e-09, 3.49245965e-09, 3.72529030e-09, 4.19095159e-09,
       4.19095159e-09, 5.12227416e-09, 6.98491931e-09, 7.45058060e-09,
       1.11758709e-08, 1.30385160e-08, 1.67638063e-08, 1.67638063e-08,
       1.86264515e-08, 2.23517418e-08, 2.42143869e-08, 2.60770321e-08,
       5.21540642e-08, 5.96046448e-08, 5.96046448e-08, 2.38418579e-07,
       3.87430191e-07, 7.74860382e-07, 8.34465027e-07, 1.19209290e-06,
       1.31130219e-06, 1.54972076e-06, 3.09944153e-06, 1.17964800e+06])

In [20]:
diff[-2]

np.float64(3.0994415283203125e-06)

In [21]:
diff[-1]

np.float64(1179648.0)