### 测试 jax.lax.exp2 算子

In [1]:
import torch
import jax.numpy as jnp
import numpy as np
import jax

In [2]:
# data = np.load("/Users/haifeng/Program/FUEL-JAX/input/jax.lax.exp2/00.npz")
# x = data['x']
# x
rng = np.random.default_rng(0)
x = rng.normal(size=(1024, 1024)).astype(np.float32)

In [3]:
j_x = jnp.array(x, dtype=jnp.bfloat16)
t_x = torch.from_numpy(x).to(torch.bfloat16)

In [4]:
j_out = jax.lax.exp2(j_x)
j_out

Array([[1.09375, 0.914062, 1.55469, ..., 1.42188, 0.474609, 0.792969],
       [1.39844, 3.0625, 0.582031, ..., 0.683594, 1.14062, 1.23438],
       [1.74219, 1.09375, 1.24219, ..., 0.917969, 0.738281, 1.45312],
       ...,
       [1.07812, 3.40625, 0.878906, ..., 0.917969, 0.742188, 0.347656],
       [2.60938, 3.95312, 0.707031, ..., 4.375, 0.3125, 0.632812],
       [0.777344, 0.691406, 0.464844, ..., 0.984375, 2.14062, 0.566406]],      dtype=bfloat16)

In [5]:
t_out = torch.ops.aten.exp2.default(t_x)
t_out

tensor([[1.0938, 0.9141, 1.5625,  ..., 1.4219, 0.4746, 0.7930],
        [1.3984, 3.0625, 0.5820,  ..., 0.6836, 1.1406, 1.2422],
        [1.7422, 1.0938, 1.2500,  ..., 0.9180, 0.7383, 1.4531],
        ...,
        [1.0781, 3.4219, 0.8750,  ..., 0.9180, 0.7422, 0.3477],
        [2.6094, 3.9531, 0.7070,  ..., 4.4062, 0.3125, 0.6328],
        [0.7773, 0.6914, 0.4629,  ..., 0.9844, 2.1406, 0.5664]],
       dtype=torch.bfloat16)

In [6]:
j_out_np = np.array(j_out, dtype=np.float32)
t_out_np = t_out.detach().to("cpu").to(torch.float32).numpy()

In [7]:
j_out_np

array([[1.09375   , 0.9140625 , 1.5546875 , ..., 1.421875  , 0.47460938,
        0.79296875],
       [1.3984375 , 3.0625    , 0.58203125, ..., 0.68359375, 1.140625  ,
        1.234375  ],
       [1.7421875 , 1.09375   , 1.2421875 , ..., 0.91796875, 0.73828125,
        1.453125  ],
       ...,
       [1.078125  , 3.40625   , 0.87890625, ..., 0.91796875, 0.7421875 ,
        0.34765625],
       [2.609375  , 3.953125  , 0.70703125, ..., 4.375     , 0.3125    ,
        0.6328125 ],
       [0.77734375, 0.69140625, 0.46484375, ..., 0.984375  , 2.140625  ,
        0.56640625]], shape=(1024, 1024), dtype=float32)

In [8]:
t_out_np

array([[1.09375   , 0.9140625 , 1.5625    , ..., 1.421875  , 0.47460938,
        0.79296875],
       [1.3984375 , 3.0625    , 0.58203125, ..., 0.68359375, 1.140625  ,
        1.2421875 ],
       [1.7421875 , 1.09375   , 1.25      , ..., 0.91796875, 0.73828125,
        1.453125  ],
       ...,
       [1.078125  , 3.421875  , 0.875     , ..., 0.91796875, 0.7421875 ,
        0.34765625],
       [2.609375  , 3.953125  , 0.70703125, ..., 4.40625   , 0.3125    ,
        0.6328125 ],
       [0.77734375, 0.69140625, 0.46289062, ..., 0.984375  , 2.140625  ,
        0.56640625]], shape=(1024, 1024), dtype=float32)

In [9]:
diff = np.abs(j_out_np - t_out_np)
max_diff = np.nanmax(diff) if not np.isnan(diff).all() else 0.0
max_diff

np.float32(0.375)